### ISSUE TITLE
Battery level indicator not working

### ISSUE THREAD

**Issue by DJay-X** [YinHangCode/homebridge-mi-fan#5]
@YinHangCode Hey. As mentioned I use model ZRFFS01ZM. In your Plugin with Type "ZhiMiDCVariableFrequencyFan" https://github.com/YinHangCode/homebridge-mi-fan/issues/4#issuecomment-415407255

Unfortunately I noticed that the battery level is never shown correct. 
It's always 0% and showing up as connected to the power, even if its not.
Please find some screenshots from Elgato Eve and Apple Home App attached.
Is there anything I can do with the config.json to fix this or any change you have an idea to change something in the Plugin if it is even possible to show battery level correct?

Thanks in advance.

```
{
            "platform": "MiFanPlatform",
            "deviceCfgs": [
                {
                    "type": "ZhiMiDCVariableFrequencyFan",
                    "ip": "192.168.178.64",
                    "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    "fanName": "Standventilator",
                    "fanDisable": false,
                    "temperatureName": "room temperature",
                    "temperatureDisable": true,
                    "humidityName": "room humidity",
                    "humidityDisable": true,
                    "buzzerSwitchName": "fan buzzer switch",
                    "buzzerSwitchDisable": true,
                    "ledBulbName": "fan led switch",
                    "ledBulbDisable": true
                }
            ]
        },
```

![napkin 25 08 18 5 37 43 pm](https://user-images.githubusercontent.com/3874239/44619993-d0b24800-a88d-11e8-9178-6b8f6d2cb522.png)

**Comment by Terminator0007** [comment]
I have also same problem. And additionally no have any info about temperature and humidity, always shown ZERO . I tried to change control commands but no positive result.

**Comment by Terminator0007** [comment]
I forgot to mention about my model. I'm using Smartmi 2S Natural Fan with akku. tHis model have Platform name ZhiMiDCVariableFrequencyFan and exact my device is zhimi.fan.za4 .

**Comment by DJay-X** [comment]
Outdated. Check https://github.com/merdok/homebridge-xiaomi-fan
